disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Logtus"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2006-01-02"
description = "Logtus | algolkk"