[[main]]
name = "About"
pageRef = "about"
weight = 1

[[main]]
name = "Posts"
pageRef = "posts"
weight = 2

[[main]]
name = "Links"
url = "https://links.algolkk.com"
weight = 3

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 10

[[footer]]
  name = "Categories"
  pageRef = "categories"
  weight = 20

